language: android
sudo: false
before_install:
- nvm install 9
- node --version
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
install:
- yarn install
jdk:
- oraclejdk8
android:
  components:
  - build-tools-26.0.2
  - android-26
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-23
  - tools
  - platform-tools
  - extra
  licenses:
  - android-sdk-license-.+

script: ./gradlew connectedAndroidTest