language: android
sudo: false
before_install:
- nvm install 9
- node --version
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
cache: yarn
install:
- yarn install
jdk:
- oraclejdk8
android:
  components:
  - build-tools-26.1.1
  - android-26
  - extra
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-26
  - tools
  - platform-tools
  - tools
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script: 
- npm run test
